# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pnfKZkTihgxKH69nSqaQ-1A71Ez_KSfm
"""

a = int(input())
if (a> 10 and a<=20 ):
  print("a est superieur a la moyenne ")
elif (a==10):
  print("a egale a la moyenne ")
elif (a>=0 and a<10):
  print("a est sous la moyenne")
else :
  print("a est une donnée aberante ")